//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yumi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public string manhanvien { get; set; }
        public string maquanly { get; set; }
        public string ten { get; set; }
        public string chucvu { get; set; }
    
        public virtual Quanly Quanly { get; set; }
    }
}
